apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
  {{- if eq .Values.env "prod" }}
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a prod configmap Index file </h1>
    </html
  {{- else if eq .Values.env "test" }}
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a test configmap Index file </h1>
    </html
  {{- else if eq .Values.env "dev" }}
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a dev configmap Index file </h1>
    </html
  {{- end }}
  
